### ISSUE TITLE
Add Lightfall

### ISSUE THREAD

**Issue by IceColdTray** [saboooor/fork-graph#5]
https://github.com/ArclightPowered/lightfall
https://github.com/ArclightPowered/lightfall-client

Waterfall fork that supports modern forge versions with a custom client/launcher.

**Comment by shibahaczix** [comment]
well it got removed now!

**Comment by saboooor** [comment]
Yeah i removed it because it falls under the category of fabric/forge server software with bukkit api mashed into it (see how magma isn't in the graph)
