### ISSUE TITLE
Add CanaryClassic, CanaryMod Recode

### ISSUE THREAD

**Issue by 44trent3** [saboooor/fork-graph#6]
https://github.com/CanaryModTeam/CanaryClassic

https://github.com/CanaryModTeam/CanaryMod

Canary Classic is a direct fork and descendant of hMod. As such it would be quite simply an hMod fork.

In regards to the other one, it is considered Canary Recode, it is a a completely rewritten version implementing CanaryLib API on 1.8, and 1.7, and 1.6. Essentially in the hierarchy of the fork graph, this would be next to Canary Classic, but *not* a fork, more like Minecraft -> CanaryMod.

They are old but historically relevant to something like this, IMO.

**Comment by saboooor** [comment]
is there a logo for it
